### ISSUE TITLE
Правильно понимать дисциплину взаимодействия по задачам

### ISSUE THREAD

**Issue by wldmr-key** [AvGustA/Cinephile#6]
Если ты закрываешь задачу, значит, ты теряешь к ней интерес - она решена. Я, разумеется, тоже. Тебя не интересует мое мнение по концептуальной схеме? Если так, то я, конечно, не настаиваю

**Comment by AvGustA** [comment]
Не в коем случае! Я случайно жамкнул(

**Comment by wldmr-key** [comment]
так, жми обратно! А эту задачу, раз правильно понял, можешь закрывать ))
